{% set name = "epicsmacrolib" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fce340c4e290824b9999118a7d1d9dfe58a334c71e9ae871266c51a235b46547

build:
  skip: true  # [py<39]
  entry_points:
    - epicsmacrolib = epicsmacrolib.bin.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=45
    - setuptools_scm >=6.2
    - cython
  run:
    - python

test:
  imports:
    - epicsmacrolib
  commands:
    - epicsmacrolib --help

about:
  home: https://github.com/pcdshub/epicsmacrolib
  license: LicenseRef-BSD-3-Clause-SLAC AND EPICS
  license_family: BSD
  license_file:
    - LICENSE
    - src/LICENSE
  summary: EPICS-compliant macro expansion tools
  description: |
    EPICS-compliant macro expansion tools for Python which will produce
    identical results to those seen in the IOC (input-output controller) shell.

extra:
  recipe-maintainers:
    - zllentz
    - tangkong
    - klauer
